// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace tSQLtTools
{
    internal sealed partial class Vsix
    {
        public const string Id = "a5b0936b-aa04-472b-8b11-776c2dbbc077";
        public const string Name = "tSQLt Tools";
        public const string Description = @"Just a few tools to make using [tSQLt ](https://tsqlt.org) easier for database unit tests in Visual Studio SQL Projects. 
The Goal is to make SQL unit testing as much like C# just in TSQL. 
No GUI with code behind and clicking just code.
";
        public const string Language = "en-US";
        public const string Version = "0.6.6";
        public const string Author = "Rogue-Archivists";
        public const string Tags = "SQL, SSDT, Database, Database Development, tSQLt, CI";
    }
}
