// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace tSQLtTools
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidtSQLtToolsPackageString = "8d5deb5f-75bb-4956-b1aa-831898433f36";
        public static Guid guidtSQLtToolsPackage = new Guid(guidtSQLtToolsPackageString);

        public const string guidtSQLtToolsPackageCmdSetString = "dc07a335-c898-44a0-a612-9a8ed3d9dec4";
        public static Guid guidtSQLtToolsPackageCmdSet = new Guid(guidtSQLtToolsPackageCmdSetString);

        public const string guidImagesString = "5d5a2558-d75a-4912-b121-34e15be1385a";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ToolMenuGroup = 0x1020;
        public const int addNewTestId = 0x0100;
        public const int addUnitTestProjectId = 0x0101;
        public const int ProjectAddCtxGroup = 0x1013;
        public const int ItemCtxGroup = 0x1014;
        public const int ProjSettingsID = 0x1015;
        public const int PushItemID = 0x1016;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}